In [1]:
from __future__ import print_function
from __future__ import division        # 精确除法
from __future__ import absolute_import # 绝对路径

# Import tensorflow as tf

In [2]:
import tensorflow as tf

## Tensor? Flow?
`tensor`是张量的意思,顾名思义,是一个能够存储多维数组的`tensorflow`数据结构,它的元素可以是`int`类型,`float`类型,`bool`类型,还有`string`类型等等.

`flow`是流动的意思,`tensor`为什么可以`flow`呢?我们通过官网的例子来一探究竟.

In [3]:
a = tf.constant(32)
b = tf.constant(10)
c = tf.add(a, b)
sess = tf.Session()
print(sess.run(c))
sess.close()

42


**上面**这段代码看上去非常简单,从结果上来看是在计算一个数学表达式`32+10` 的值,却也完整展示了`tensorflow`运行的基本构架.

首先,第一行`a = tf.constant(32)`定义了一个常量`tensor`,它的值为`32`,第二行也是类似.在我们运行`tensorflow`程序的时候,任何数据都必须转换成`tensor`类型才能够进入这个系统,我们先牢记这一点,之后会对它进行优缺点分析.那么现在我们就有了两个常量`tensor`.

但是仅仅定义了两个用于存储数据的`tensor`毫无用处,我们希望能够实现的是这两个数的加法运算.相信大家小时候学数学加减法的时候老师都会在黑板上作出这样的图:

<img src="https://image.ibb.co/jmcSfG/basic_add.png" width="200">

这张图揭示了加法运算的过程,通过`+`这个符号将两个数连接起来,并生成了一个新的数.

这正是`tensorflow`致力于实现的目标,通过`tf.add()`这个函数,将两个`tensor`连接起来并生成了一个新的`tensor`:`c`.实际上,定义在一个或者多个`tensor`上的函数在`tensorflow`中被封装成`operator`的概念.还可以发现,加法只是一个关于两个数和一个操作的关系,对于输入的数据是`1,2`还是`32,10`完全不会有任何本质改变. 因此, 整个计算图以符号计算的定义方式, 被封装成了`Graph`,也就是图的概念.

<img src="https://image.ibb.co/gjZgSc/tf_add_graph.png" width="200">

到这里, 我们通过构建两个`tensor`以及一个`operation`完成了一个`Graph`的创建. 这些是我们运行`tensorflow`程序的标准步骤, 但还并没有结束. 大家可以尝试运行下面这行代码, 看看它的输出是什么.

In [4]:
print(a)
print(b)
print(c)

Tensor("Const:0", shape=(), dtype=int32)
Tensor("Const_1:0", shape=(), dtype=int32)
Tensor("Add:0", shape=(), dtype=int32)


此时相信我们中的大部分都会心里产生巨大的疑惑, 怎么会输出这么一堆看不懂的东西, 我只是想让它像定义时那样输出`32, 10, 42`就好了啊, 难道我的`print`函数坏掉了?无论你如何进行尝试, 你会发现都没有出现你想要的结果, 因为就像刚才说的, 在`tensorflow`下, 所有的`tensor`都是一种符号, 用来构建整个`Graph`的, 它是什么值并不重要, 所以就无法在构建图之后进行打印看它的值了.

但这显然不是我们想要看到的, 如何才能正确打印这些值呢? 事实上, `tensorflow`将构建图和执行图分成了两个独立的步骤, 也就是说你要先构建一个完整的计算图, 此时你无法获取图的具体信息, 但是随后你可以开始进入图的执行过程, 这样你就可以获得图执行时每个`tensor`的具体值了. 怎样进入图的执行呢?

### 开启`Session`(会话)!

In [5]:
sess = tf.Session()

简单的`sess = tf.Session()`就可以搞定. 开启会话后, 我们就可以执行图中的各个`tensor`了, 用的正是`sess.run()`这个语句.

现在我们可以试试下面这些命令了:

In [6]:
print(sess.run(a))
print(sess.run([a, b]))
print(sess.run([a, b, c]))

32
[32, 10]
[32, 10, 42]


我们可以将执行图的结果保存到正常的变量中, `tensorflow`称这个过程为`fetch`. 运行下面的命令, 相信你会对`fetch`有一个初步的了解.

In [7]:
py_a = sess.run(a)
print(type(py_a))
print(py_a)
py_r = sess.run([a, b, c])
print(type(py_r))
print(py_r[0], py_r[1], py_r[2])

<class 'numpy.int32'>
32
<class 'list'>
32 10 42


#### `Tensors`
`tensor`可以有很多形式.

In [8]:
hello = tf.constant('Hello, Tensorflow!')
boolean = tf.constant(True)
int_array = tf.constant([1, 2], dtype=tf.int32)
float_array = tf.constant([1, 2], dtype=tf.float32)

print(sess.run(hello))
print(sess.run(boolean))
print(sess.run(int_array))
print(sess.run(float_array))

b'Hello, Tensorflow!'
True
[1 2]
[1. 2.]


#### 练习1
构造一个`tensor`, 使得输出一个`numpy`矩阵[[1 0] [0 1]]

#### 答案1

In [9]:
mat = tf.constant([[1,0],[0,1]])
print(sess.run(mat))

[[1 0]
 [0 1]]


`tensor`还可以有**名字**, 在定义每个`tensor`的时候添加参数**`name`**的值就可以.这是一个可选参数, 不过在后面有很大的意义

In [10]:
my_name_is_hello = tf.constant('Hello', name='Hello')
my_name_is_world = tf.constant('World', name='World')

print('tensor {}: {}'.format(my_name_is_hello.name, sess.run(my_name_is_hello)))
print('tensor {}: {}'.format(my_name_is_world.name, sess.run(my_name_is_world)))

tensor Hello:0: b'Hello'
tensor World:0: b'World'


#### `Operations`
`tensorflow`原生支持很多的`operation`, 以后我们将用`op`来简称`operation`. 注意, `op`也可以有名字用来标识.

In [11]:
d = tf.add_n([a, b, b])
e = tf.subtract(a, b)
f = tf.multiply(a, b)
g = tf.divide(a, b)
h = tf.mod(a, b)

print(sess.run(d))
print(sess.run(e))
print(sess.run(f))
print(sess.run(g))
print(sess.run(h))

52
22
320
3.2
2


In [12]:
a_float = tf.cast(a, dtype=tf.float32)
b_float = tf.cast(b, dtype=tf.float32)

i = tf.sin(a_float)
j = tf.exp(tf.divide(1.0, a_float))
k = tf.add(i, tf.log(i))

print(sess.run(i))
print(sess.run(j))
print(sess.run(k))

0.5514267
1.0317434
-0.043819606


#### 练习2
构造一个`tensor`, 它的值等于$sigmoid(b)$, `sigmoid`函数如下定义
$$
\begin{equation}
\sigma(x) = \frac{1}{1 + e^{-x}}
\end{equation}
$$
它的函数图像(摘自[Wiki](https://en.wikipedia.org/wiki/Sigmoid_function))如下所示:
<img src="https://image.ibb.co/cH5c0x/practice2_sigmoid.png" width="360">

#### 答案2

In [13]:
sigmoid = tf.divide(1.0, tf.add(1.0, tf.exp(-b_float)))
print(sess.run(sigmoid))

0.9999546


- 可以通过`reshape`改变形状
- `tensorflow`支持矩阵操作,`broadcast`机制

In [14]:
mat_a = tf.constant([1, 2, 3, 4])
mat_a = tf.reshape(mat_a, (2, 2))
mat_b = tf.constant([1, 3, 5, 7, 9, 11])
mat_b = tf.reshape(mat_b, (2, 3))
vec_a = tf.constant([1, 2])

mat_c = tf.matmul(mat_a, mat_b)
mat_d = tf.multiply(mat_a, vec_a)

print(sess.run(mat_a))
print(sess.run(mat_b))
print(sess.run(mat_c))
print(sess.run(mat_d))

[[1 2]
 [3 4]]
[[ 1  3  5]
 [ 7  9 11]]
[[15 21 27]
 [31 45 59]]
[[1 4]
 [3 8]]


#### numpy_like `tensors`
`tensorflow`采用了很多类似于`numpy`的数据定义方式

In [15]:
zeros = tf.zeros((2, 3), dtype=tf.int32)
zeros_like = tf.zeros_like(zeros)
ones_like = tf.ones_like(zeros)
fill = tf.fill((2, 4), 2)
linspace = tf.linspace(1.0, 5.0, 5)
ranger = tf.range(3, 18, delta=3)

print('{}:\n{}\n'.format('zeros', sess.run(zeros)))
print('{}:\n{}\n'.format('zeros_like', sess.run(zeros_like)))
print('{}:\n{}\n'.format('ones_like', sess.run(ones_like)))
print('{}:\n{}\n'.format('fill', sess.run(fill)))
print('{}:\n{}\n'.format('linspace', sess.run(linspace)))
print('{}:\n{}\n'.format('range', sess.run(ranger)))

zeros:
[[0 0 0]
 [0 0 0]]

zeros_like:
[[0 0 0]
 [0 0 0]]

ones_like:
[[1 1 1]
 [1 1 1]]

fill:
[[2 2 2 2]
 [2 2 2 2]]

linspace:
[1. 2. 3. 4. 5.]

range:
[ 3  6  9 12 15]



#### `random tensors`
`tensorflow`有很多`random`算子

In [16]:
rand_normal = tf.random_normal((), mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)
truncated_normal = tf.truncated_normal((), mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)
rand_uniform = tf.random_uniform((), minval=0.0, maxval=1.0, dtype=tf.float32, seed=None)

for i in range(5):
    print('time: %d' % i)
    print('rand_normal: %.4f' % sess.run(rand_normal))
    print('truncated_normal: %.4f' % sess.run(truncated_normal))
    print('rand_uniform: %.4f' % sess.run(rand_uniform))

time: 0
rand_normal: 0.7901
truncated_normal: 1.4687
rand_uniform: 0.4510
time: 1
rand_normal: -1.5295
truncated_normal: 0.7395
rand_uniform: 0.2626
time: 2
rand_normal: 0.9341
truncated_normal: -0.5260
rand_uniform: 0.6590
time: 3
rand_normal: -0.4914
truncated_normal: -0.1449
rand_uniform: 0.2189
time: 4
rand_normal: 1.8895
truncated_normal: 1.1365
rand_uniform: 0.8893


### 关闭`Session`
`session`可以打开就需要被关闭, 用下面这行命令

In [17]:
sess.close()

### Variables
前面的这些是`tensorflow`的一些常量`tensor`, 通常来说它们一旦被定义就无法更改. 在我们训练机器学习模型的时候, 最重要的一步便是更新参数, 这些常量`tensor`无法满足. 

那么我们就需要变量(`variables`).先看看变量如何定义.

In [18]:
var_a = tf.Variable(0, dtype=tf.int32)
var_b = tf.Variable([1, 2], dtype=tf.float32)
var_w = tf.Variable(tf.zeros((1024, 10)))

**每个**变量都有一个`initializer`的函数, 规定这个变量的初始值是什么. 因此, 在执行图的过程中必须要**先初始化**变量后才能够使用. 可以通过下面的这些方法进行初始化

在此之前, 我们先了解一下`tensorflow`的交互式`session`:**`InteractiveSession()`**,在处理`variable`的时候, 它比普通的`Session`更为灵活一点

In [19]:
##开启交互式`session`
sess = tf.InteractiveSession()

##一次性初始化所有的变量
init = tf.global_variables_initializer()
###一般`session`的方法
sess.run(init)
###`InteractiveSession`的方法
init.run()

##初始化某些变量
init_ab = tf.variables_initializer([var_a, var_b])
init_ab.run()

## 初始化某个变量
var_w.initializer.run()

初始化完成后仍然不能打印值, 需要用`session`去`run`这个`variable`,或者是调用`InteractiveSession`下面的**`eval()`**函数, 大家观察一下下面输出的不同

In [20]:
W = tf.Variable(10)
sess.run(W.initializer)
print(W)
print(sess.run(W))
print(W.eval())

<tf.Variable 'Variable_3:0' shape=() dtype=int32_ref>
10
10


**`assign`**是为`variable`赋值的一个`op`,大家可以看下面的代码来理解`operation`和`assign`的应用

In [21]:
W.assign(100)
W.initializer.run()
print(W.eval(sess))

10


In [22]:
assign_op = W.assign(100)
W.initializer.run()
assign_op.eval()
print(W.eval())

100


**`assign_add`**和**`assign_sub`**对应与我们平常理解的`i++`和`i--`, 也是`variable`的常用`op`

In [23]:
assign_add = W.assign_add(10)
assign_sub = W.assign_sub(2)

W.initializer.run()
print(assign_add.eval())
print(assign_add.eval())
print(assign_sub.eval())
print(W.eval())

20
30
28
28


- name_scope和variable_scope

我们可以给一些 tensor 添加一个名称域，这样所有的变量名称都有一个共同的前缀. 

我们可以通过`tf.name_scope`或者`tf.variable_scope`来实现

In [24]:
with tf.name_scope('name_scope'):
    var_a = tf.Variable(0, dtype=tf.int32)
    var_b = tf.Variable([1, 2], dtype=tf.float32)
with tf.variable_scope('var_scope'):
    var_c = tf.Variable(0, dtype=tf.int32)
    var_d = tf.Variable([1, 2], dtype=tf.float32)
print(var_a.name)
print(var_b.name)
print(var_c.name)
print(var_d.name)

name_scope/Variable:0
name_scope/Variable_1:0
var_scope/Variable:0
var_scope/Variable_1:0


### Placeholders
在前面我们介绍计算图的时候, 我们注意到构建图的时候可以脱离具体值进行定义它的整体结构, 在运行的时候可以根据需要带入具体的数值. 可是前面我们定义的常量`tensor`以及变量`tensor`都需要一个初始值. 因此, 为了更加契合图的构建过程, `tensorflow`引入了一个**占位符**.(`placeholder`)的概念. 字如其面, 它只是占着构建图的一个位置,没有具体数值, 但必须要有具体的类型以及形状. 我们来看看这个古怪的东西是如何定义的吧.

In [25]:
##定义一个占位符
##`tf.placeholder(dtype, shape=None, name=None)`

# 定义一个`float32`型的占位符,它是一个长为3的向量
a = tf.placeholder(tf.float32, shape=[3])

# 定义一个`bool`型的占位符, 它是一个`1x2`的矩阵
b = tf.placeholder(tf.bool, shape=[1, 2])

如果我们还像之前那样企图用`a.eval()`的话, 就会体会到`placeholder`的特别之处, 因为它真的没有任何值! 实际上,在执行图的过程中, 我们必须要用字典的方式给`placeholder`喂入具体值, 这个过程称为**`feed`**. 

表现在程序中, 就是我们在获取一个占位符的值的时候, 需要给`run()`增加一个`feed_dict`的参数, 这个参数是一个`dict`, 它的`key`是占位符的变量名, 它的`val`是需要喂入的具体值. 当然, 这个字典可以有很多个`key`, 也就是说可以一次喂入很多个占位符.

In [26]:
print(sess.run(a, feed_dict={a: [1, 2, 3]}))
print(sess.run([a, b], feed_dict={a: [1, 2, 3], b: [[True, False]]}))

[1. 2. 3.]
[array([1., 2., 3.], dtype=float32), array([[ True, False]])]


占位符也是一个`tensor`,因此它可以被`op`作用, 可以和其他`tensor`混合在一起使用. 这样, 图的构建也就完整了.

#### 练习3
构造一个数值占位符, 当喂入的元素是1, 2, 4, 8时, 输出这个占位符的平方

#### 答案3

In [27]:
a = tf.placeholder(tf.float32)
square = tf.square(a)
for i in [1, 2, 4, 8]:
    print(square.eval(feed_dict={a:i}))
    
for i in [1,2,3,4]:
    print(sess.run(a, feed_dict={a:i*i}))

1.0
4.0
16.0
64.0
1.0
4.0
9.0
16.0


### tf.Graph
最后我们再来看一下`tensorflow`里图的概念. 前面说了, 在执行图之前, 需要将整个计算图都构建完成, 那么我们如何才能获得这个完整的图呢? 

In [28]:
g = tf.get_default_graph()
print(g)

好了, 得到这个图之后, 我们当然可以往前回溯我们创建过的图的每一个节点, 通过`g.get_operations()`就可以查到所有的节点. 我们还可以通过`g.get_tensor_by_name()`获得对应`name`的`tensor`

In [29]:
for op in g.get_operations():
    print(op.name)

Const
Const_1
Add
Const_2
Const_3
Const_4
Const_5
Const_6
Hello
World
AddN
Sub
Mul
truediv/Cast
truediv/Cast_1
truediv
FloorMod
Cast
Cast_1
Sin
truediv_1/x
truediv_1
Exp
Log
Add_1
Neg
Exp_1
Add_2/x
Add_2
truediv_2/x
truediv_2
Const_7
Reshape/shape
Reshape
Const_8
Reshape_1/shape
Reshape_1
Const_9
MatMul
Mul_1
zeros
zeros_like
ones_like/Shape
ones_like/Const
ones_like
Fill/dims
Fill/value
Fill
LinSpace/start
LinSpace/stop
LinSpace/num
LinSpace
range/start
range/limit
range/delta
range
random_normal/shape
random_normal/mean
random_normal/stddev
random_normal/RandomStandardNormal
random_normal/mul
random_normal
truncated_normal/shape
truncated_normal/mean
truncated_normal/stddev
truncated_normal/TruncatedNormal
truncated_normal/mul
truncated_normal
random_uniform/shape
random_uniform/min
random_uniform/max
random_uniform/RandomUniform
random_uniform/sub
random_uniform/mul
random_uniform
Variable/initial_value
Variable
Variable/Assign
Variable/read
Variable_1/initial_value
Variable_1
Varia

In [30]:
what_is_this = g.get_tensor_by_name('Hello:0')
print(what_is_this.eval())

b'Hello'


In [31]:
sess.close()

#### 生成新图
上面介绍了`tensorflow`运行程序时的默认图, 那么我们可以构造有别于默认图的新图吗? 当然可以的, 通过**`g1=tf.Graph()`**就可以办到. 但这并没有结束, 我们需要将这个图设置为我们构造`tensor`以及`op`的默认图, 让程序能够理解我们将要定义的`tensor`到底在哪个图里定义, 因此我们还需要通过`python`的`with`语句来确立图的作用范围.然后我们可以通过变量的`.graph`属性来确定它在哪个图中, 

In [32]:
##定义一个新图, 注意它和之前的g有什么不同
g1 = tf.Graph()
print('g1: ', g1)

##将这个新图作为默认图,注意前后默认图有没有不同
print('default_graph: ', tf.get_default_graph())
g1.as_default()
print('default_graph: ', tf.get_default_graph())

##在这个新图后面定义新的`tensor`
a1 = tf.constant(32, name='a1')

with g1.as_default():
    a2 = tf.constant(32, name='a2')

##查看`tensor`从属的图
print('a.graph: ', a.graph)
print('a1.graph: ', a1.graph)
print('a2.graph: ', a2.graph)

g1:  <tensorflow.python.framework.ops.Graph object at 0x0000019F703C4748>
default_graph:  <tensorflow.python.framework.ops.Graph object at 0x0000019F701CBA90>
default_graph:  <tensorflow.python.framework.ops.Graph object at 0x0000019F701CBA90>
a.graph:  <tensorflow.python.framework.ops.Graph object at 0x0000019F701CBA90>
a1.graph:  <tensorflow.python.framework.ops.Graph object at 0x0000019F701CBA90>
a2.graph:  <tensorflow.python.framework.ops.Graph object at 0x0000019F703C4748>


#### 图的可视化
现在我们要迫不及待的给大家介绍`tensorflow`的一款神器**`tensorboard`**!它在我们安装`tensorflow`的过程中就已经被自动安装了, 非常方便.

在它的帮助下, 我们可以将刚才我们构造的图可视化, 让它变得更加清晰直观.

- 首先我们需要将我们想要可视化的图导入到`tensorboard`可以解析的文件中

In [33]:
with tf.Session() as sess:
    graph_writer = tf.summary.FileWriter('.', sess.graph)

这个时候在当前目录中你就会多一个`events.*`的文件, 这个就是需要的文件.

- 然后我们在当前目录打开终端(一般来说是右键, 点击`Open in New Terminal`或者是`在终端中打开`),键入以下命令:

```
$ tensorboard --logdir=.
```

- 然后就会有一个这样的输出

```
$ TensorBoard 0.1.8 at http://USERNAME:6006 (Press CTRL+C to quit)
```

- 然后我们打开浏览器（用chrome浏览器）, 输入`at`后面的链接`http://USERNAME:6006`,进入.你就会发现这样的界面

<img src="https://image.ibb.co/juk2iH/tensorboard_graph.png">

- 然后我们就可以尽情的探索里面的内容了

## 结语
至此, 我们完成了`tensorflow`的初步概览. 接下来我们将要进入深度学习环节.